default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "rails") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  database: <%= ENV.fetch("DB_NAME", "aact_new") %>

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "rails") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  database: <%= ENV.fetch("DB_NAME", "aact_new_test") %>


production:
  <<: *default
  url: <%= ENV["DB_URL"] %>

external:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("EXTERNAL_DB_POOL", 5) %>
  host: <%= ENV.fetch("EXTERNAL_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("EXTERNAL_DB_PORT", 5432) %>
  username: <%= ENV.fetch("EXTERNAL_DB_USER", "external_user") %>
  password: <%= ENV.fetch("EXTERNAL_DB_PASSWORD", "external_password") %>
  database: <%= ENV.fetch("EXTERNAL_DB_NAME", "external_db") %>