default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  database: <%= ENV.fetch("DB_NAME", "aact_new") %>
  username: <%= ENV.fetch("DB_USER", ENV['USER']) %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "aact_new") %>_test

production:
  <<: *default
  url: <%= ENV["DB_URL"] %>

# aact core db currently has data for building documentation for aact-admin
external:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["AACT_CORE_DB_URL"] %>